defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "v1"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "v1"
  -
    scope:
      path: "case-studies"
      type: "posts"
    values:
      layout: "case-study"
permalink: none
teams:
  leadership:
    id: 'leadership'
    label: 'Leadership'
  dd:
    id: 'dd'
    label: 'Dream Directors'
  innovation:
    id: 'innovation'
    label: 'Innovation'
  california:
    id: 'california'
    label: 'California'
  chicago:
    id: 'chicago'
    label: 'Chicago'
  connecticut:
    id: 'connecticut'
    label: 'Connecticut'
  detroit:
    id: 'detroit'
    label: 'Detroit'
  newark:
    id: 'newark'
    label: 'Newark'
  nyc:
    id: 'nyc'
    label: 'New York'
  philly:
    id: 'philly'
    label: 'Philadelphia'
  dc:
    id: 'dc'
    label: 'Washington, DC'
  hq:
    id: 'hq'
    label: 'Headquarters'
  board:
    id: 'board'
    label: 'Board of Directors'
  advisors:
    id: 'advisors'
    label: 'Advisors'
